.github/workflows/containers.yml, docker/network/functional/Dockerfile.centos-8, docker/network/functional/Dockerfile.centos-9, docker/network/integration/Dockerfile.centos-8, docker/network/integration/Dockerfile.centos-9, docker/network/unit/Dockerfile.centos-8, docker/network/unit/Dockerfile.centos-9
In order to be up to date with centos changes, build
the containers every automatically every Monday on midnight.
Add also manual trigger for the build so the containers
can be rebuild manually if needed.
=> automation: Automatically build network containers

.github/workflows/network.yml, tests/network/nettestlib.py
Add network tests that will be triggered only when
something in network code changes, there is no need
to run them with every vdsm change as the functional
tests can take a while.
=> automation: Add network tests

lib/vdsm/virt/vm.py
In commit c63867bbd416f5b52cd8cc27a3e3557dc558394a
vm: Replace blockInfo with block stats
We introduced a regression, using the wrong physical size from the
source drive instead of the apparentsize of the replica disk. This may
cause to register wrong block threshold, which will cause a VM to pause
during disk replication.
=> vm: Fix VM._amend_block_info()

lib/vdsm/API.py, lib/vdsm/api/vdsm-api.yml, lib/vdsm/storage/constants.py, lib/vdsm/storage/hsm.py, lib/vdsm/storage/sd.py, lib/vdsm/storage/sp.py, lib/vdsm/storage/volume.py, lib/vdsm/storage/volumemetadata.py, tests/storage/blocksd_test.py, tests/storage/localfssd_test.py, tests/storage/sdm_indirection_test.py, tests/storage/volume_metadata_test.py
This PR adds the new sequence field to a volume's metadata. This value will be increased for every volume created in an image and will be used to determine which volume is the correct leaf when multiple leaves are present (In operations like snapshot preview and disk convert). 
Depends on https://github.com/oVirt/vdsm/pull/33
=> Bug 977778: Introduce volume sequence

lib/vdsm/storage/nbd.py, tests/storage/nbd_test.py
qemu-6.2 introduce a regression in extent reporting when using
--allocation-depth option. Avoid this issue by using this option
only for qcow2 format.
Running the nbd tests with qemu-6.2 revealed another change in
zero detection in qcow2 image. Update the test so they pass in
6.2 or earlier versions.
The nbd tests depends on running supervdsm manually, and it moved
recently without updating the comment.
=> Update for qemu 6.2

static/etc/modules-load.d/vdsm.conf
When PCI pass-through is used and vfio-pci module is employed for the
devices it is useful to pre-load the module and don't wait for something
else to load it. Without the module engine does not show any module in
PCI devices list which is not too user friendly.
Change-Id: Ia3dd2fd01e87a847eb6d19d6b6f15ea1d327be24
Bug-Url: https://bugzilla.redhat.com/1960808
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
=> static: load vfio-pci module

lib/vdsm/api/vdsm-api.yml, lib/vdsm/virt/migration.py
libvirt added the capability of using several parallel migration
connections to speed up migrations.  This patch adds support for a new
migration parameter `parallel' to use the feature.
It is expected that Engine will provide maxBandwidth argument to
maximize throughput when parallel connections are requested.  If
maxBandwidth is not provided, the default Vdsm limit is applied as
usual.
It is possible to explicitly disable parallel migration connections by
setting the `parallel' parameter to 0.  This can be useful if implicit
parallel migration connection setting for a VM is introduced in
future and we need to disable it for a particular migration.
Note that it is meaningful to set the number of parallel migration
connections to 1.  In such a case, the feature is enabled for the …
=> virt: Add support for parallel migration connections

.github/workflows/containers.yml
The containers workflow fails every week in my vdsm fork because the
ovirt organization secrets are not available in forks. Skip the push to
quay if repository owner is not 'oVirt'.
Example run from my fork, suceeded without pushing to quay:
https://github.com/nirs/vdsm/actions/runs/1740212112
=> github: Don't try to push to quay on forks

.github/workflows/containers.yml
When we set:
can_push: ${{ github.repository_owner == 'oVirt' }}
Github converts the boolean value to the strings 'true' or 'false'[1],
so checking:
if: ${{ env.can_push == true }}
Does not match and now we never push to quay.
Example run on my fork show that we still skip the push on forks:
https://github.com/nirs/vdsm/actions/runs/1740365670
Unfortunately, the only way to test this properly is to merge to master.
[1] https://docs.github.com/en/enterprise-server@3.0/actions/learn-github-actions/expressions#functions
Fixes 746975bb434e5fbb4c41c3e119728bc3322fb5e9
=> github: Fix can_push condition

.github/workflows/ci.yml
In order to use RPMs on OST we need to adopt the common
naming. Use oVirt upload artifacts action that keeps
the convention in one place.
=> Use oVirt upload artifacts action

lib/vdsm/common/dsaversion.py.in
As a part of 05eefda9703ec21a87428d4c8a552eb019f28101 we have introduced
cluster level 4.7, which requires libvirt >= 7.10.
But recently libvirt has been updated to 8.0, which should be the version
included in RHEL 8.6 and CentOS Stream 9. So we are bumping cluster level
4.7 to require libvirt >= 8.0
Bug-Url: https://bugzilla.redhat.com/2021545
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Modify support for cluster level 4.7

lib/vdsm/network/dhcp_monitor.py
The message was logged with warning, which results in some confusion
and spam in the journal. Let's have it as debug as the intention
is really to know what was happening with the monitoring.
=> net: Lower severity of nic not configured for monitoring

docker/network/functional/Dockerfile.centos-8, docker/network/functional/Dockerfile.centos-9, docker/network/integration/Dockerfile.centos-8, docker/network/integration/Dockerfile.centos-9, docker/network/unit/Dockerfile.centos-8, docker/network/unit/Dockerfile.centos-9
The tag for build container has changed and the container itself
grew in size. With packages for JavaScript and Java there is no
point in keeping it as base.
=> automation: Update network containers to use centos as base

lib/vdsm/storage/lvm.py, tests/storage/lvm_test.py
Fix lvm suppressing tests, and fix new warning we introduced recently
by adding the "--driverloaded n" option in lvextend.
=> Suppress lvm warnings

lib/vdsm/virt/vm.py, tests/virt/vmoperations_test.py
VM.getChunkedDrives() is not used since 2017, remove it.
Fixes: 6a251845f4a237b9c9b78e5d7461bcd9c6184c3b
=> vm: Remove ancient unused method

.github/workflows/ost.yml
Start OST run for current pull request when adding a comment like:
/ost
We need to improve this later so only maintainers can start OST or
starting OST is possible only if the patch is approved.
replaceing PR: https://github.com/oVirt/vdsm/pull/44
=> github: Add OST workflow

CODEOWNERS, doc/thin-provisioning.md, lib/vdsm/clientIF.py, lib/vdsm/storage/sp.py, lib/vdsm/virt/jobs/snapshot.py, lib/vdsm/virt/livemerge.py, lib/vdsm/virt/migration.py, lib/vdsm/virt/periodic.py, lib/vdsm/virt/thinp.py, lib/vdsm/virt/vm.py, lib/vdsm/virt/vmdevices/storage.py, tests/virt/diskreplicate_test.py, tests/virt/drive_extension_test.py, tests/virt/livemerge_test.py, tests/virt/thinp_test.py, tests/virt/vmmigration_test.py
Preparing for monitoring scratch disks, refactor the code to related
to monitoring drives so it can monitor volumes.
Work in progress, posted as draft for early review.
=> Prepare for monitoring scratch disks

lib/vdsm/common/config.py.in, lib/vdsm/storage/Makefile.am, lib/vdsm/storage/lvmdevices.py, lib/vdsm/storage/lvmfilter.py, lib/vdsm/tool/config_lvm_filter.py, tests/storage/lvmfilter_test.py
[LVM devices](https://man7.org/linux/man-pages/man8/lvmdevices.8.html) file is a new way how specify devices which should be used by LVM and is a replacement for LVM filter. LVM devides file is optional on RHEL 8.5 and the default on RHEL 9. However, LVM filter can still be used if needed. Once LVM is configured to use devices file, LVM filter is ignored, even if explicitly specified.
This enhancement will implement LVM devices file configuration and usage in vdsm and is tracked by [BZ #2012830](https://bugzilla.redhat.com/2012830).
As it's very hard to configure the LVM filter in vdsm and in some case we have to ask user to do it manually, using devices files allows us to simplify host configuration and upgrade flows and therefore is preferred way how to specify LVM devices. As mentioned …
=> lvm devices file configuration

.github/workflows/ost.yml
The current if condition always matches, so every comment will trigger
OST run.
For example, this comment:
https://github.com/oVirt/vdsm/pull/49#issuecomment-1028473401
Triggered this run:
https://github.com/oVirt/vdsm/actions/runs/1786861822
I could not find documentation for this but the issue is metioned here:
https://github.community/t/how-to-write-multi-line-condition-in-if/128477
Looks like "|" and "${{}}" do not work together. For multi-line if we
should use only "|".
Fixes: 588a421d1c97d6eeb5784a162a72bca5f05dd15f
=> github: Fix OST condition

docker/network/functional/Dockerfile.centos-8, docker/network/functional/Dockerfile.centos-9, docker/network/integration/Dockerfile.centos-8, docker/network/integration/Dockerfile.centos-9, docker/network/unit/Dockerfile.centos-8, docker/network/unit/Dockerfile.centos-9
For some reason the built done by GH actions
won't install systemd in the el9 contianers, however
the local one does that. Add the systemd dependency explicitly
to prevent that issue.
=> net: Add systemd to all network containers

lib/vdsm/virt/thinp.py, lib/vdsm/virt/vm.py, tests/virt/drive_extension_test.py, tests/virt/thinp_test.py
Clean up the API after we moved all the monitoring and extending code
to thinp.VolumeMonitor.
- Remove unneeded optional arguments
- Make methods private
- Move last lefover monitoring code from VM
- Remove duplication
- Avoid unneeded calls to VM methods
- Unify methods names
- Group methods by category.
Based on top of #58.
=> Cleanup VolumeMonitor API

lib/vdsm/storage/hsm.py, lib/vdsm/storage/lvm.py, lib/vdsm/storage/managedvolume.py, tests/storage/lvm_test.py, tests/storage/managedvolume_test.py
This is follow-up patch of PR #27.
PR #27 introduced new lvm configuration, which uses devices file instead lvm filter. Not to touch user devices accidentally, vdsm allows lvm to use only local devices and all other devices are by default excluded by lvm filter configured by vdsm. For each lvm command vdsm provides lvm config where vdsm sets lvm filter where given device upon lvm command should act is explicitly enabled. However, once lvm is configured to use devices file, lvm filter is ignored.
With devices files we can achieve same result by adding only local devices into lvm devices file (done in PR #27) and then explicitly allow devices in lvm commands by providing `--devices $dev1, ..., $devN` argument in lvm commands. This is implemented in this PR - when vdsm is configured to use …
=> Use lvm devices in lvm commands instead of filter

lib/vdsm/storage/lvmconf.py, lib/vdsm/storage/lvmdevices.py, lib/vdsm/storage/lvmfilter.py, tests/storage/lvmconf_test.py
Currently path to lvm devices files is hardcoded in lvmdevices module and uses default lvm value. This would break if the user for some reason configures lvm to use custom devices file. This PR:
* add new function which allows to determine lvm config value which will be actually used by lvm
* replace hardcoded path to lvm devices file by one actually used by lvm
* does some minor cleanup, especially reuse existing constant pointing to lvm executable instead of defining it again in each module using lvm command
=> Don't use hardcoded value for lvm devices file

lib/vdsm/common/config.py.in
Switch the default from filter based LVM configuration to devices file
configuration. Any newly installed host or host upgraded to vdsm version
containing this commit will start to use LVM devices file and LVM filter
will be ignored.
If the user has any issue with this setup, it can be reverted by
creating custom vdsm config file (or modifying if such file already
exists) and setting config_method to "filter" in lvm section, e.g.:
$ cat /etc/vdsm/vdsm.conf.d/99-lvm.conf
[lvm]
config_method= filter
Change-Id: Ib4d814fe42e5e0f2b75ed0d6f974c756b7605ad6
Signed-off-by: Vojtěch Juránek <vjuranek@redhat.com>
=> lvm: use devices file as default config method

lib/vdsm/network/tc/filter.py, tests/network/unit/tc_filter_show.out
Newer version of iproute-tc (>=5.15.0-3) omits the
"???" from the filter output. Include also "not_in_hw"
for potential consume, this will ensure that both formats
are accepted e.g. ".. terminal flowid ??? not_in_hw .."
and ".. terminal flowid not_in_hw ..". One important thing
to note, it is safe to consume "not_in_hw" because the value
is skipped otherwise by the parser.
=> net: Fix tc tokens parsing

lib/vdsm/storage/hsm.py, lib/vdsm/storage/storageServer.py, tests/storage/hsm_connect_test.py
Don't fail when engine sends empty connection list on storage server disconnect. This happens when multiple iSCSI SDs use same iSCSI target and therefore it cannot be disconnected as it's still used by other SDs. Engine should be fixed not to send disconnect request in such case, but we need to handle older engines. Log warning in such case, do nothing and return empty list as calling code expects iterable with results..
On the other hand engine always sends non-empty connection list when connecting SD. If the list is empty for some reason when connecting storage server, also log warning, but let vdsm throw `KeyError` as this is unexpected.
Fixes https://bugzilla.redhat.com/2054745
=> Don't fail when connection list is empty

lib/vdsm/common/time.py, lib/vdsm/virt/thinp.py, lib/vdsm/virt/vmdevices/storage.py, tests/common/time_test.py
Include the time since the the block threshold event was received until
we handled it in the extend timing log.
Based on the timing info we can tune the volume extension parameters to
minimize vm pauses, both in vdsm defaults and in the fields in the defaults
need to be changed for a particular environment.
To improve the timing info, vdsm.comon.time.Clock was modified to allow
timing since a time in the past.
Bug-Url: https://bugzilla.redhat.com/2051997
=> Improve extend timing

.github/workflows/network.yml
By running tests after the container is built we can find any possible
regression caused by newer packages in the container.
=> network: Run network tests every week after new containers are built

lib/vdsm/api/vdsm-api.yml, lib/vdsm/virt/backup.py, tests/virt/backup_test.py
Add to VDSM API and use 3 new properties that will allow creating scratch disk on block storage with small initial size.
VDSM will monitor the scratch disk block threshold and extend it as needed.
Signed-off-by: Pavel Bar <pbar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1913389
=> Minimize scratch disk initial size

lib/vdsm/common/config.py.in, tests/storage/blockvolume_test.py, tests/storage/merge_test.py, tests/virt/thinp_test.py
Collecting extend stats shows that extend takes between 2.2 to 6.2
seconds, with average of 3.7 seconds. With the default thresholds:
[irs]
volume_utilization_chunk_mb = 1024
volume_utilization_percent = 50
This means that we extend the volume when free space is 512 MiB. Writing
more than 512 MiB in 3.7 seconds (138.4 MiB/s) will cause the VM to
pause with ENOSPC.
This configuration was too low 10 years ago, and we need to update it
for modern storage. Update the values to allow 4 times faster writes
before we pause with ENOSPC.
With the new configuration:
[irs]
volume_utilization_chunk_mb = 2560
volume_utilization_percent = 20
We extend the volume when free space is 2048 MiB.
Testing with old and new configuration show that we can cope now with 4x
times faster write rate before we VMs …
=> config: Increase thin provisioning threshold

lib/vdsm/API.py, lib/vdsm/api/vdsm-api.yml, lib/vdsm/storage/blockSD.py, lib/vdsm/storage/blockVolume.py, lib/vdsm/storage/fileVolume.py, lib/vdsm/storage/hsm.py, lib/vdsm/storage/sd.py, lib/vdsm/storage/sp.py, lib/vdsm/storage/volume.py, tests/storage/blocksd_test.py, tests/storage/glance_test.py, tests/storage/localfssd_test.py, tests/storage/sdm_indirection_test.py
When creating a new volume or a snapshot, caller can specify
bitmap={bitmap-uuid} to create a new empty bitmap in the new volume.
This will enable hybrid backup, when every backup is started by creating
a temporary snapshot. The new bitmap records the changes to the volume
since the snapshot was created. When the temporary snapshot will be
deleted, the new bitmap will be copied to the parent volume, and will be
used for the next incremental backup.
Like add_bitmaps, we treat creating a new bitmap as best effort. If the
operation fails we don't fail the creation of the volume, but the next
backup using this bitmap will have to be a full backup.
Not tested yet, but tests pass.
Bug-Url: https://bugzilla.redhat.com/2053669
=> Support adding a bitmap to new volume

lib/vdsm/tool/configurators/multipath.py
When using Ceph, multipath might prevent the rbd device from being
unmapped and it stays mapped.
It results with getting the following error while operating the disk:
rbd.ImageBusy: [errno 16] RBD image is busy
This patch adds rbd to the multipath blacklist.
Bug-Url: https://bugzilla.redhat.com/1881832
Bug-Url: https://bugzilla.redhat.com/1755801
Signed-off-by: Shani Leviim [sleviim@redhat.com](mailto:sleviim@redhat.com)
=> Add a blacklist for rbd devices

lib/vdsm/common/hostdev.py, lib/vdsm/supervdsm_api/virt.py, lib/vdsm/virt/vmdevices/hostdevice.py, tests/hostdev_test.py, tests/hostdevlib.py
Engine is going to add a new metadata item for vGPU devices,
mdevDriverParameters.  It specifies driver parameters to be set when
the mediated device is created, by writing a file in /sys.
The driver consumes the last character written to the file in /sys, so
it is important to write a new line character at the end, as `echo'
from a shell command line would do.
Since mediated devices are created before each use and destroyed after
each use, it's enough to write the driver parameters, if specified,
only when the device is created.  It's not necessary to clear them
when the device is removed, although it is possible to do it by
writing a space to the driver parameters file in /sys.
Currently, only NVidia driver parameters are supported.  If setting
driver parameters is attempted for other …
=> virt: Add support for vGPU driver parameters

lib/vdsm/storage/nbd.py, tests/storage/nbd_test.py
When exporting bitmap from single volume, we did not validate that
the bitmap exists and valid. When staring qemu-nbd service, qemu-nbd
starts normally so we report success, but then it fails and exits.
Later, the user fail when trying to download the backup.
Another issue, we created an overlay when exporting a volume with a parent
when the parent volume does not include the bitmap. This case does not
require an overlay.
- Add failing tests for bitmap validation
- Add bitmap validation when exporting single volume
- Create overlay only if needed
=> NBD bitmap validation with single volume

lib/vdsm/tool/configurators/multipath.py
When running multipath we see new warnings:
Mar 15 03:11:33 | ignoring extra data starting with 'devices,' on line 119 of /etc/multipath.conf
Mar 15 03:11:33 | /etc/multipath.conf line 119, invalid keyword: Blacklist
Mar 15 03:11:33 | ignoring extra data starting with 'be' on line 120 of /etc/multipath.conf
Mar 15 03:11:33 | /etc/multipath.conf line 120, invalid keyword: should
Recent change in multipath replaced part of a comment with text; comment
it properly.
Fixes a08988ed30538b32f87b198120b27d98ba7e3de1
=> multipath: Fix generated multipath.conf

docker/network/Makefile, docker/network/functional/Dockerfile.centos-9, docker/network/integration/Dockerfile.centos-9, docker/network/unit/Dockerfile.centos-9
The copr packages were signed by SHA1 which was
removed on el9s, until the relevant BZ [0] is fixed
set crypto policy to lagacy.
[0] https://bugzilla.redhat.com/2059101
=> net: Add crypto policy workaround for el9s

lib/vdsm/api/vdsm-api.yml, lib/vdsm/virt/domain_descriptor.py, lib/vdsm/virt/migration.py, lib/vdsm/virt/vm.py, tests/virt/vmoperations_test.py
Necessary code and API changes to allow migration of NUMA VMs. It has to be possible to adapt the NUMA pinning during migration because CPUs on destination host may be used differently or destination host may have different hardware. Similarly it is necessary to allow modification to manual CPU pinning to limit virtual NUMA cells to corresponding physical NUMA cells.
=> Numa migration

lib/vdsm/network/nmstate/ovs/network.py, lib/vdsm/network/nmstate/state.py, tests/network/unit/nmstate/testlib.py
The openvswitch does not accept '""' and complains
about it, change it to simple empty string instead.
=> net: Fix empty OVN bridge mappings

lib/vdsm/virt/vmdevices/storage.py, lib/vdsm/virt/vmdevices/storagexml.py
During Direct LUN disk hotplug with SCSI Reservation, Reservation is
not enabled. The configuration received by vdsm from the engine
contains the 'reservations' parameter, but the one transferred to
libvirt - does not.
Found that this parameter is not supported neither in vmdevices/storagexml.py
when desalinizing config from the engine, nor in vmdevices/storage.py when
serializing config for libvirt, thus this configuration is not passed to libvirt on
hotplug.
Added support for the 'reservations' parameter support both to vm
metadata deserialization and serialization.
Bug-Url: https://bugzilla.redhat.com/2028481
=> Add SCSI reservations support to hotplug API

tests/virt/device_test.py, tests/virt/vmstorage_test.py
These tests cover parsing VM XML for Direct LUN hotplug with SCSI
Reservations, Drive creation and serializing to XML for libvirt
Related to https://github.com/oVirt/vdsm/pull/105
=> Adding tests for hotplug with SCSI reservations

contrib/extend-stats, lib/vdsm/common/config.py.in, lib/vdsm/host/caps.py, lib/vdsm/storage/mailbox.py, tests/storage/mailbox_test.py, tests/storage/stress/thinp.py
Minimize message latency by introducing mailbox an events mechanism.
The unused host 0 mailbox is used now for sending and receiving mailbox
events.
- Hosts write an event to host 0 mailbox after sending mail to the SPM.
- The SPM monitors host 0 mailbox every eventInterval (0.5 seconds)
between monitor intervals, so it can handle new messages quickly.
- When hosts wait for reply from the SPM, they monitor their inbox every
eventInterval (0.5 seconds), so they detect the reply quickly.
- Host reports a new "mailbox_events" capability. This can be used by
engine to optimize mailbox I/O when all hosts in a data center
supports this capability.
- Extend roundtrip latency reduced from 2.0-4.0 seconds to 0.5-1.0 seconds.
- Total time to extend a volume decreased from 2.3-5.9 seconds to 0.9-3.3 …
=> mailbox: Minimize messages latency

lib/vdsm/api/vdsm-api.yml
Recent arguments added to the schema were missing the "added" property.
=> api: Add missing added info

lib/vdsm/virt/vmdevices/storage.py
From going over the code of the `storage.py` file, I saw a few typos in the comments.
No-effort fix, improves searching (i.e., search by "chunked" word).
Signed-off-by: Pavel Bar <pbar@redhat.com>
=> Fix comments typos in '`storage.py`'

tests/storage/stress/thinp.py
Make the thinp test script easier to use for testing, and nicer as
example for RHV demo.
- Add command line arguments so there is no need to edit the script.
- Fix short write - previously short write would be ignored, reporting
incorrect actual rate and total size.
- Fix actual rate - previously did not consider throttling.
- Add correction time for throttling, considering the time to sleep and
get the next timestamp in the next sleep.
- Round the actual rate for more stable results.
Example usage with this change:
$ python tests/storage/stress/thinp.py --rate 1024 --size 10 thinp.data
10.00 GiB, 10.00 s, 1024.1 MiB/s
=> tests: Refine thinp stress test

lib/vdsm/storage/fileVolume.py
When creating preallocated volume with size <= 4096, we try to allocate
0 bytes:
/usr/libexec/vdsm/fallocate --offset 4096 0 /path...
Which fail in fallocate() with EINVAL as expected, and then we raise
VolumesZeroingError: Cannot zero out volume: /path...
It looks like engine does not handle this error correctly, and the disk
remain locked forever.
Creating a volume of 4k bytes or less is not a real use case, but there
is no technical reason why it should fail. Fixed by skipping the
allocation if we don't have anything to allocate.
Reported-by: Janos Bonic <jpasztor@redhat.com>
=> fileVolume: Fix creation of tiny volumes

lib/vdsm/storage/mailbox.py
There is a typo here: "Recived"
2022-04-07 09:38:48,661+1000 INFO  (mailbox-spm) [storage.MailBox.SpmMailMonitor] Recived event: dea59300-f65a-485c-90f6-227d9c2823cc (mailbox:857)
=> mailbox: fix typo on event receiving log

tests/README
- Add command to recreate tox environments with no test execution
- Fix small syntax issues
=> Update tests README

vdsm.spec.in
ppc64le is not shipping qemu-kvm anymore.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
=> spec: exclude ppc64le on el9

lib/vdsm/storage/mailbox.py, static/etc/vdsm/logger.conf.in
The mailbox logs were always noisy, but with mailbox event they are too noisy.
This change:
- Add separate storage_mailbox logger configuration, so enabling DEBUG logs for storage does not enable mailbox logs
- Silence common logs that log too much detail or use wrong log level
- Run commands with storage.mailbox logger, so we can control the logging using logger.conf
- Run all commands with same runner so we can use the same logger for all mailbox commands
- Use same logger for all mailbox classes, logger per class is not needed
Fixes #135
=> Silence mailbox logs

contrib/target
When creating a target, the default portal (0.0.0.0:3260) is created. To
multipath properly we need to create multiple portals, using multiple ip
addresses or ports.
Add --portal argument, allowing to create a portal listening to specific
address:port, or multiple portals.
Here is an example command:
--lun-count 1 \
--cache \
--portal 192.168.122.34 \
--portal 192.168.122.35
Creating target
target_name:   05
target_iqn:    iqn.2003-01.org.alpine.05
target_dir:    /target/05
lun_count:     1
lun_size:      100 GiB
cache:         True
exists:        False
portals:       192.168.122.34:3260, 192.168.122.35:3260
Create target? [N/y]: y
...
This crates a target with 2 portals:
o- iqn.2003-01.org.alpine.05 ......................................... [TPGs: 1]
o- tpg1 …
=> Support multiple portals

lib/vdsm/storage/sdm/api/copy_data.py, lib/vdsm/storage/sdm/api/update_volume.py
Fixes #107 
**Verified** by triggering the `copy_data` behavior from the engine web UI by both copying and moving disks:
One host was running with the `vdsm-client` installed and updated from RPMs. In both cases the operation succeed.
=> copy_data: Consolidate semantically equal endpoint params

Makefile.am, README.md, doc/development.md, tests/README.md, tests/storage/README.md
Create a new developer's README similar to other projects (e.g., ovirt-imageio). This change slightly improves readability
information's organization. In the update is important to keep the files linked so that it is easy to find information
and navigate between the different documentation files.
This PR includes an update of the tests README to markdown format and the update of some sections before
moving them to the new developer's document. Here's a summary of the changes:
1. Transform the **tests** `README` file to `README.md` and change format to fully comply with Markdown syntax.
2. Remove outdated parts from the original README
3. Create a developer's readme in the doc folder and move all developer-specific sections from main `README.md` and `test/README.md` to …
=> Create a developer's readme

tests/storage/misc_test.py
Fixes: #143
Changes:
- Add additional checks to verify the return value on tests that execute commands in misc_tests
- Remove copyrighted texts from misc_tests
- Avoid using checkSudo in misc_tests, use `@requires_root` decorator instead
=> misc_test: Check ret code and improve sudo check 

doc/thin-provisioning.md, lib/vdsm/virt/periodic.py, lib/vdsm/virt/thinp.py, lib/vdsm/virt/vm.py, lib/vdsm/virt/vmdevices/storage.py, tests/virt/thinp_monitor_test.py, tests/virt/thinp_test.py, tests/virt/vmstorage_test.py
This is the first part from #124, preparing for eliminating the the delay
before extending drives (#85). The changes were reviewed in the last 3 weeks
and should be ready for merge.
Fixes:
- Fix handling of block threshold events
- Fix handling of enospc events
- Fix the way we force drive to exceeded
- Fix extending of exceeded volume, was delayed checking stale allocation
Improvements:
- Improve handling of improbable allocation
- Validate allocation only when needed
- Unify logging
Refactoring:
- Simplify the way we update block info for drives
- Simplify monitor_volumes, removing unhelpful return value and logging.
- Remove VM.monitor_volumes, minimizing coupling with vm.py
- Introduce on_enospc event handler, unifying the way we handle libvirt events.
- Report changes in Drive event …
=> Prepare for eliminating delay on extend

automation/check-patch.packages, docker/network/unit/Dockerfile.centos-8, docker/network/unit/Dockerfile.centos-9, vdsm.spec.in
With changes to nmstate-2.1 the python3-libnmstate
is not installed by default. This causes issues for
the unit tests as they need the library to work properly.
Add the python3-libnmstate as explicit dependency into
spec file as well, to be clear that this is required.
=> net: Add python3-libnmstate as explicit dependency

tests/storage/lvm_test.py
Some commands in lvm_tests try to force the configuration by passing the `--config` option, whereas they should adapt to it and use `--devices` instead.
Fixes #163 (covers solution 1)
=> lvm_tests: use --devices instead of --config in commands

lib/vdsm/storage/lvm.py, tests/storage/lvm_test.py
This branch adds a couple tests to slightly improve code coverage for VG-handling methods in the `lvm` module.
Includes a small fix for a typo in the `lvm` library.
=> lvm_test: increase vg test coverage

lib/vdsm/network/netswitch/configurator.py
The tuple returned from split_switch_type
was not properly assigned to variables.
This caused the if statement to be always true,
it did not cause any issues, but the network capabilities
were also getting OvS info which wasn't necessary.
Assign it properly so only the first dictionary is used.
=> net: Fix the tuple assign

lib/vdsm/common/config.py.in, lib/vdsm/virt/periodic.py, lib/vdsm/virt/thinp.py, lib/vdsm/virt/vm.py, lib/vdsm/virt/vmdevices/storage.py, tests/virt/thinp_monitor_test.py, tests/virt/thinp_test.py
When receiving a block threshold event or when pausing because of ENOSPC,
extend the drive as soon as possible.
This change decreases the wait before sending an extend request from 0.0-2.0
seconds to 10-30 milliseconds.
Here are test results from 4 runs, each writing 50 GiB to think disk at
~1300 MiB/s. Each run extends the disk 20 times. The VM was not paused
during the test.
| time        |  min  |  avg  |  max  |
|-------------|-------|-------|-------|
| total       |  0.77 |  1.15 |  1.39 |
| extend      |  0.55 |  0.92 |  1.14 |
| refresh     |  0.16 |  0.22 |  0.31 |
| wait        |  0.01 |  0.01 |  0.03 |
Fixes: #85
=> Eliminate the wait before extending a volume

lib/vdsm/gluster/cli.py, tests/gluster_cli_test.py
gluster: fix compatibility with Gluster v10 or greater
In gluster v10 or greater stripe count is removed and when
stripe count is not returned from the volume info command
setting the stripeCount to default value that is 1
Fixes: #155
Bug-Url: https://bugzilla.redhat.com/2078569
Signed-off-by: Ritesh Chikatwar <rchikatw@redhat.com>
=> gluster: fix compatibility with Gluster v10 or greater,

lib/vdsm/storage/blockVolume.py, lib/vdsm/storage/constants.py, lib/vdsm/storage/merge.py, tests/storage/blockvolume_test.py, tests/storage/merge_test.py
When preparing for merge, we extend the base volume in a dumb way, allocating too much space. We clean up when finalizing the merge, so the volume size is optimal when the merge is done. However during the merge the over allocation can cause the storage domain to become full which can cause vms to fail to extend their disks, or to other storage operation to because storage space is low.
This change fix the issue by measuring the required size for the merge, and calculating the optimal size of the volume based on the required size. When the merge is finalized the volume should be in the optimal size so we don't need to shrink the volume.
Fixes #134
=> Fix over allocation when preparing merge

lib/vdsm/storage/blockVolume.py, lib/vdsm/storage/merge.py, tests/storage/blockvolume_test.py, tests/storage/merge_test.py
When computing optimal size during finalize, if the top volume is a leaf
(active layer merge), the base volume will become leaf after the merge.
Compute the optimal size as if the base volume is a leaf.
Fixes #179
=> Fix reduce after active layer cold merge

lib/vdsm/storage/blockSD.py
BlockStorageDomainManifest._validatePVsPartOfVG receives
a 'pv' argument that is shadowed in a dict comprehension
in the first line of the method. It might be safe as it
is contained in the comprehension only, but shadowing
should be avoided anyway.
Also, 'pv' is wrong in the comprehension, since listPVNames
will return a PV path (not a PV namedtuple). So changing
'pv' for 'path' in the comprehension will both fix the
argument shadowing and use proper informative naming.
=> blockSD: avoid argument shadowing in validatePVs

lib/vdsm/storage/exception.py, lib/vdsm/storage/lvm.py, tests/storage/exception_test.py, tests/storage/lvm_test.py
Currently, if we try to reload a non-existing VG that is not in the cache, we will not get any error, it will raise an exception without any context of the actual reason of the fail.
Furthermore, if the LVM command fails, it might go unnoticed, or trigger a single uninformative warning without the reason why it might have failed.
Make _reloadvgs to raise an exception if the LVM command failed and there is no output. Then, the caller will decide whether it is a real error or it was just probing.
Add tests to verify the behavior of all parts of `lvm` module that are affected by the error handling update.
Related https://github.com/oVirt/vdsm/pull/159
=> lvm: reload VG error handling

lib/vdsm/storage/blockSD.py, lib/vdsm/storage/merge.py, tests/storage/blocksd_test.py, tests/storage/merge_test.py
When finalizing a merge, only the format (cow) and the `optimal_size` are considered to discern when to reduce a volume. However, calculating the optimal size can be avoided in the case of a preallocated block volume, as it cannot be reduced.
Also, in the StorageDomain, `reduceVolume` can be called with no check at all, which is dangerous.
Use the volume `can_reduce` check before obtaining the optimal size, and before reducing the volume (both in the cold merge and the storage domain), so that we consider the type of volume before reducing it.
Fixes: https://github.com/oVirt/vdsm/issues/185
Bug-Url: https://bugzilla.redhat.com/2081493
=> merge: consider type when reducing a volume

Makefile.am, doc/development.md
Add `venv` target to the main Makefile to create a virtual environment and install the dependencies.
=> Makefile: add venv target

lib/vdsm/virt/guestagent.py, lib/vdsm/virt/vm.py
We used to transfer some guest statistics to destination host before
migration. This disappeared from the code for non-obvious reasons while
moving to domain XML on engine (commit 88c6922f). Stored statistics
where username (logged in user), guestFQDN (hostname) and guestIPs
(network addresses). This commit restores transfer of username and
guestFQDN. Instead of guestIPs we transfer netIfaces, which provides
more detailed information about interfaces, and also because guestIPs is
not used in engine since 4.2.
Bug-Url: https://bugzilla.redhat.com/1853897
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
=> virt: store some guest stats during migration

lib/vdsm/network/link/nic.py, lib/vdsm/network/tc/_parser.py, tests/network/functional/net_qos_test.py, tests/network/integration/tc_test.py, tests/network/unit/netinfo_test.py, tox.ini
Latest click versions are not compatible with black
version used by tox (21.6b0). To fix it we either
have to move to a more recent version of black, which
currently breaks the linter in some tests, or we downgrade
the version of click to 8.0.2.
See https://github.com/psf/black/issues/2964 for context.
Error seen when running `make lint`:
```
Traceback (most recent call last):
File "/home/aesteve/Work/ws1/vdsm/.tox/black/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/home/aesteve/Work/ws1/vdsm/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 1127, in patched_main
patch_click()
File "/home/aesteve/Work/ws1/vdsm/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 1113, in patch_click
from click import _unicodefun  # type: ignore
ImportError: …
```
=> tox.ini: allow newer black version to match click version

lib/vdsm/storage/blockVolume.py, lib/vdsm/storage/lvm.py, tests/storage/lvm_test.py
`LVM.removeLV` is not used anymore and can be safely removed.
As a consequence, `LVMCache._reloadlvs` is used only for reloading all the LVs (the cost is roughly the same as reloading only one), so we can drop the support for reloading a single LV.
=> lvm: remove renameLV and support for single LV reloading

lib/vdsm/API.py, lib/vdsm/api/vdsm-api.yml, lib/vdsm/clientIF.py, lib/vdsm/common/udevadm.py, lib/vdsm/storage/managedvolume.py, lib/vdsm/supervdsm_api/udev.py, tests/storage/managedvolume_test.py
The current code for attaching MBS devices tries to construct stable
path. This works for RBD and mpath devices, however doesn't scale for
drivers that do not fall in this category, for instance, NVMe/TCP
drivers.
This patch create a link for the path returned by os-brick, this link
will be managed by vdsm and will be used by engine as the path to run
VMs.
Link example:
```shell
ll /var/run/vdsm/managedvolumes/fa728e08-2db4-4016-bfbb-bd75f2ee1735_876fa465-d92b-4070-833d-c5ec4331ceb5
lrwxrwxrwx. 1 vdsm kvm 60 May  3 10:21 /var/run/vdsm/managedvolumes/fa728e08-2db4-4016-bfbb-bd75f2ee1735_876fa465-d92b-4070-833d-c5ec4331ceb5 -> /dev/rbd/volumes/volume-876fa465-d92b-4070-833d-c5ec4331ceb5
```
Snippet for VM XML:
```xml
<disk type='block' device='disk' snapshot='no'>
<driver name='qemu' …
```
=> managedvolume: create link for MBS devices

lib/vdsm/storage/hsm.py, lib/vdsm/virt/livemerge.py, lib/vdsm/virt/thinp.py, lib/vdsm/virt/vm.py, tests/virt/livemerge_test.py, tests/virt/vmfakelib.py
In live merge we used a dumb way to extend the base volume before the merge, resulting
in growing the active volume by at lest 2 chunks for every live merge.
Fix by measuring the required size before the merge using the new capability to measure
a sub chain and active volume (#101).
With this change the active volume grows only if there is less then one chunk of free
space after the merge, and there is no need to shutdown the VM to reclaim unused space.
Fixes #188
Related-to: https://bugzilla.redhat.com/1993235
=> Fix over extend in live merge

lib/vdsm/storage/exception.py, lib/vdsm/storage/lvm.py, tests/storage/exception_test.py
`LVMCache._reloadvgs` has been recently refactored for better error handling.
This branch extends the same strategy to `reloadpvs`:
- Refactor the method, according to its function:
- Run LVM command
- Try to reload stale PVs
- Update all PVs
- Split reload into single and multi PVs
- Raise exceptions for missing volumes from the LVMCache, only when looking for specific volumes
- Callers should get either a valid volume or propagate an exception
Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)
=> lvm: error handling in reloadpvs consistent with VGs

lib/vdsm/common/config.py.in, lib/vdsm/virt/vm.py, tests/virt/data/disk_devices.xml, tests/virt/vmmigration_test.py
When a migrating VM is being prepared on the destination host, some
disks require modifying and reloading udev rules on the host.  This
can take a significant amount of time and if the VM has a lot of such
disks then a migration preparation timeout may occur.
The right solution would be to reload the modified rules only once for
all the disks.  But this would require some more work to implement.
At the moment, let’s make a workaround prolonging the migration
preparation timeout per each such a disk.  But not beyond a newly
configurable max_migration_listener_timeout.
We add 2 seconds per drive by default.  This is an arbitrarily
selected value that would work well in an environment where the
problem was observed.  If this value doesn’t work well enough in some
environment, it can be …
=> virt: Prolong migration listener timeout by disk preparation

lib/vdsm/storage/volume.py
Previously we requires create=True only for qcow2 images using
compat=0.10 that do not support zero clusters. This issue is not
relevant since RHEL 8.4.
Testing convert of big qcow2 image (8 TiB) show that writing zero
clusters is not fast enough for big images. When qemu-img convert
creates the target image, it knows that the image is zeroed, so it can
skip unallocated areas instead of zeroing them.
Testing copy of 8 TiB empty image shows that without -n the copy is 700
times faster:
real    2m1.839s
user    0m10.383s
sys     0m7.563s
real    0m0.171s
user    0m0.111s
sys     0m0.011s
With real images we see much lower speedup. Here is an example copy with
a 8 TiB image created with virt-builder:
    --output fedora-35-8t.raw \
    --hostname=fedora-35 \
    --ssh-inject=root \
    …
=> volume: Requires create for qcow2 image without a parent

.gitignore, Makefile.am, automation/rpm.sh, doc/development.md
Add the `upgrade` target to the makefile to be able to upgrade the system with the built rpm packages by just doing:
make upgrade
Also, we move the built rpm packages from the default directory at `~/rpmbuilds` to a project-specific `build` folder, and add a `clean-build` target that is executed before building. This way we don't need to clean the folder manually, it gets cleaned when we execute `make clean` or `make rpm`.
With both new targets we can just build and deploy (upgrade) the system by doing:
make rpm upgrade
=> Makefile: add upgrade target and custom rpm build folder

static/usr/share/vdsm/lvmlocal.conf
The event_activation option set to 0 in the global
section of the lvmlocal.conf is causing el9nodes
to fail to boot after being installed by the engine.
LVM removed support for disabling event_activation in rhel9.
Existing systems with event_activation=0 that update lvm
will no longer have static autoactivation services, and
may fail to boot (if an LV required by fstab was not
activated by the initrd).
Removing the option solves the issue. The option was
not correct for el8 systems either, it is discouraged
to use since it is not reliable (may appear to work
based on timing of device attachement). Thus, this
option can be safely removed.
The global section is left with no options whatsoever,
so it can be completely removed alongside the
event_activation configuration.
Related-to: …
=> lvmlocal.conf: remove global section

static/usr/share/vdsm/lvmlocal.conf
When we change the content of the lvmlocal.conf file, we must bump the
revision. This is used by the lvm configurator to upgrade the file when
running `vdsm-tool configure` during upgrade.
Fixes: 4ec21db8ae83 (lvmlocal.conf: remove global section)
=> lvmlocal.conf: Bump revision to fix upgrade

.copr/Makefile
When building from COPR the project is cloned into temporary directory,
which is not owned by current user. From git 2.35.2 such directory needs
to be marked as safe inn order git commands work correctly.
=>  Mark temp repo directory as safe for COPR

lib/vdsm/storage/check.py, tests/storage/check_test.py
When using Popen.communicate() the process pipes are closed when the
child closes its end of the pipe. But in the check module we run
multiple processes in the same thread, and we read from the pipe using
asynchronous I/O. In this case we never close the child process pipe.
This should not be an issue, since the pipe should be closed
automatically when we remove the reference to the process, and we never
notice any file descriptor leak in this code.
However we see clear leak in the case when a storage domain becomes
inaccessible. Strangely, only failing checks from inaccessible storage
domains leak, and we see very clear leak of one file descriptor every 10
seconds:
for i in $(seq 3600); do
echo "$(date --rfc-3339=seconds), $(readlink /proc/$(pidof -x vdsmd)/fd/* | wc -l)"
sleep 10
done …
=> check: Fix fd leak when child process fails

lib/vdsm/virt/vm.py
Somehow libvirt drops `passwdValidUntil` attribute from domain XML when
when we pass XML that has no `passwd` attribute to restoreFlags(). Same
happens when restoring from snapshot with memory and we can use the same
method to mitigate the problem.
An alternative would be to pass `VIR_DOMAIN_SAVE_IMAGE_XML_SECURE` flag
to `saveImageGetXMLDesc()` call. That way libvirt would not hide the
`passwd` from us. But since our passwords to graphics console are
temporary this does not add any value. Also we would leak the console
password to the logs which is not favorable even though the password is
likely to be invalid at the time of resume.
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
=> virt: fix graphics configuration when resuming from hibernation

lib/vdsm/virt/vm.py
When resuming a live snapshot with memory the domain XML contains CPU
pinning that has been used at the time the snapshot was taken. Such
pinning is likely to be invalid when the snapshot is resumed. Engine
passes new CPU pinning configuration in API and it should be honored.
=> virt: Replace CPU pinning when resuming snapshot with memory 

lib/vdsm/storage/blockSD.py, lib/vdsm/storage/lvm.py, tests/storage/blocksd_test.py, tests/storage/lvm_test.py, tests/storage/storagefakelib.py
LVMCache._reloadvgs has been recently refactored for better error handling.
This branch extends the same strategy to `reloadlvs`:
- Refactor the method, according to its function:
- Run LVM command
- Try to reload stale LVs
- Update all LVs
- Split reload into single and multi LVs
- Raise exceptions for missing volumes from the LVMCache, only when looking for specific volumes
- Callers should get either a valid volume or propagate an exception
- Fixes #211
=> lvm: make reloadlvs consistent with VGs

lib/vdsm/storage/lvm.py
This warning is left over from times we retried the lvm command
before failing. Now we run once with specific lvm devices, and again
with all devices, so this log is not very helpful and can be removed.
Addresses the first issue in https://bugzilla.redhat.com/show_bug.cgi?id=2048545
=> lvm: remove outdated warning

lib/vdsm/storage/storageServer.py
When seting up an iscsi node for a connection fails, the error logged had a typo.
Fix and improve it by adding the reason of the error to the logs.
Fixes: https://github.com/oVirt/vdsm/issues/252
=> storageServer: fix and improve iscsi connect error logging

lib/vdsm/storage/iscsi.py, lib/vdsm/storage/iscsiadm.py
If logging in to target fails with "session exist" error, consider the
login successful.
The issue happens when a host has duplicate portals with the same
address, port, iface:
Target: iqn.2003-01.org.alpine.01
Portal: 192.168.122.34:3260,1
Iface Name: default
Portal: 192.168.122.34:3260,2
Iface Name: default
iscsiadm tries to login to both portals, but it cannot create more than
one session for the same address, port, iface, so it logs in the one of
the portals and complain about the second:
Logging in to [iface: default, target: iqn.2003-01.org.alpine.01, portal: 192.168.122.34,3260]
Logging in to [iface: default, target: iqn.2003-01.org.alpine.01, portal: 192.168.122.34,3260]
Login to [iface: default, target: iqn.2003-01.org.alpine.01, portal: 192.168.122.34,3260] successful.
iscsiadm: …
=> iscsiadm: Consider session exists as success

contrib/target
New targets always use tpgt=1, which makes it hard to simulate issues
with server that use unique tpgt tags (e.g. 1034). Add --tpgt argument
to allow creating targets with custom tpgt.
Here is an example create a target with custom tpgt:
Creating target
target_name:   05
target_iqn:    iqn.2003-01.org.alpine.05
target_dir:    /target/05
lun_count:     2
lun_size:      100 GiB
cache:         True
exists:        False
portals:       192.168.122.34:3260, 192.168.122.35:3260
tpgt:          50
Create target? [N/y]: y
This creates a target with:
alpine:~# targetcli ls /iscsi/iqn.2003-01.org.alpine.05
o- iqn.2003-01.org.alpine.05 ............................ [TPGs: 1]
o- tpg50 .................................... [gen-acls, no-auth]
o- acls ............................................. [ACLs: 0] …
=> contrib/target: Support non-default tpgt

vdsm.spec.in
There's no reason to require exactly the same vdsm version
for the hook to work. It causes issues when installing on top of
node/rhvh, so let's use a more relaxed requirement.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
=> hook-log-console: Don't require exact vdsm match

contrib/git-sync
The git-sync tool push the current branch to a remote. This is useful
for testing your changes on a host or for running the tests on a test
vm.
=> contrib: Add git-sync tool

lib/vdsm/storage/mpathconf.py, lib/vdsm/storage/multipath.py, lib/vdsm/tool/configurators/multipath.py, tests/storage/mpathconf_test.py
Move all the logic to handle, write, and check multipathd configuration from the tools.multipath module to mpathconf.
The multipath module will act as a wrapper of the mpathconf module for the vdsm-tool, and it may add some logging and
extra functionality on top of it, but the logic shall be kept in the storage.mpathconf module.
Add some tests to verify the functions that were moved.
Update/homogenize some minor parts of the code.
=> mpathconf: move logic from tools.multipath to mpathconf

lib/yajsonrpc/betterAsyncore.py
Caused by incomplete python 3 porting of the betterAsyncore module.
Also fix handle_close to always close the dispatcher. The underlying 
dispatcher implementation was not closing the dispatcher.
Log dispatcher lifetime events to make it easier to debug next time. 
Bug-Url: https://bugzilla.redhat.com/2102678
=> Fix a busy loop after socket is closed

docker/Dockerfile.centos-8, docker/Makefile
Create an unprivileged vdsm user in the container image to enable running tests as non-root.
This could be achieved by using other unprivileged user, e.g., `nobody`, but creating vdsm allows creating tests specific for vdsm user that run both in the pipelines and in the test VMs.
=> docker: add vdsm user to container image

.github/workflows/ci.yml, Makefile.am, automation/tests-storage.sh, tests/storage/blockdev_test.py, tests/storage/blocksd_test.py, tests/storage/devicemapper_test.py, tests/storage/dmsetup_test.py, tests/storage/fileutil_test.py, tests/storage/iscsiadm_test.py, tests/storage/loopback_test.py, tests/storage/lvmfilter_test.py, tests/storage/managedvolume_test.py, tests/storage/misc_test.py, tests/storage/mount_test.py, tests/storage/multipath_test.py, tests/storage/outofprocess_test.py, tests/storage/qemuimg_test.py, tox.ini
Split storage CI jobs between unprivileged `vdsm` user tests (mark non-root) and root tests.
With the numbers below we end up executing 50 more tests that were skipped before and safe more than 2 minutes in execution time.
Numbers are not averaged, only the last run is considered.
__All storage tests__
collected 2702 items / 101 deselected / 2601 selected
Required test coverage of 68% reached. Total coverage: 68.87%
`= 2472 passed, 123 skipped, 101 deselected, 5 xfailed, 1 xpassed, 1 warning in 371.31s (0:06:11) =`
__Non-root tests__
collected 2700 items / 235 deselected / 2465 selected
Required test coverage of 61% reached. Total coverage: 61.87%
`= 2402 passed, 59 skipped, 235 deselected, 4 xfailed, 1 warning in 164.30s (0:02:44) =`
__Root tests__
collected 2700 items / 2566 deselected …
=> ci: split storage ci jobs for root and non-root testing

.github/workflows/ci.yml
Update ci job test-storage to test-storage-user
to be consistent with its test-storage-root counterpart.
=> ci: update test-storage job name

lib/vdsm/virt/periodic.py
VM external data, if not provided by Engine, may not be available
initially and may be created only once the VM is started by libvirt.
If its retrieval is attempted before the data is available, an error
message is produced in the logs.  This error message is harmless but
incorrect and it may confuse users or prevent distinguishing real
errors from fake errors.
Let’s not retrieve external data in all the VM initial states, not
only MIGRATION_DESTINATION, to prevent the external data retrieval
error.
=> virt: Don’t retrieve VM external data until the VM is started

configure.ac, execcmd-allowlist.txt, vdsm.spec.in, vdsm_hooks/Makefile.am, vdsm_hooks/log_firmware/Makefile.am, vdsm_hooks/log_firmware/README, vdsm_hooks/log_firmware/before_vm_start.py
This is a combination of the interface of log-console and the
functionality of qemucmdline, hard-coded to log the firmware output to a
log file. qemucmdline can't be used directly for HostedEngine, because
we want a separate log file per VM, and qemucmdline does not have
internally functionality to allow doing that, relying instead on the
engine to supply correct params somehow. For HostedEngine, we can't rely
on the engine, as it does not exist at this point.
Change-Id: I5e2324009daed5136ab7884226cce0feee2e0c96
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
=> hooks: Add log-firmware

lib/vdsm/vdsmd.py
When using export domain we use safelease instead of sanlock. During
fencing flows, it sends SIGUSR1 signal to vdsm to stop the SPM.
=> vdsmd: Document why we handle SIGUSR1 signal

lib/vdsm/common/panic.py, lib/vdsm/vdsmd.py, tests/storage/stress/release-spm-lease.py
We tried to add a timeout using signal.alarm() to make that vdsm will
panic if shutting down logging hangs. However this does not work, since
the alarm is delivered to the main thread instead of the thread setting
the alarm.
What actually happened after we added the alarm was:
1. Panic thread: calls signal.alarm(10)
2. Panic thread: calls logging.shutdown(), call hangs
3. Main thread: crash with "RuntimeError: Alarm timeout"
When we removed zombiereaper, we also removed the SIGALRM signal handler
by mistake, so what happens in current code is:
1. Panic thread: calls signal.alarm(10)
2. Panic thread: calls logging.shutdown(), call hangs
3. Unhandled SIGALRM terminates the process
Replace the broken alarm with a thread waiting on an event.
Fixes: 56ed0796259a (panic: Limit time spent …
=> panic: Fix panic when logging.shutdown hang

lib/vdsm/storage/blockVolume.py, tests/storage/blocksd_test.py
blockVolume getParent method uses the volume tag
PU_<id> to obtain the parent. However, this tag
could be outdated. For example, when the host
syncs a volume chain after removing a volume,
it only updates the metadata. Afterwards,
the SPM will update the volume tag once the
volume is deleted.
To ensure we do not return outdated parent UUID,
we need to ensure that the parent UUID obtained
from the parent tag, and the UUID in the volume
metadata match, and log a warning and update
the volume otherwise.
Tested with ovirt-stress: https://gitlab.com/nirs/ovirt-stress/-/merge_requests/14
It consistently triggered the bug in each run. After upgrading with this
branch patch, it passed each iteration (tried 10 iterations).
In the logs it can be seen:
```
2022-07-21 16:30:21,503+0200 WARN …
```
=> blockVolume: check parent tag and meta match

lib/vdsm/storage/mpathconf.py, lib/vdsm/storage/multipath.py, lib/vdsm/tool/configurators/multipath.py, tests/storage/mpathconf_test.py
This PR updates the isconfigured check for the multipath in the vdsm-tool,
so that running:
Will print a WARN message if there is any device or section in the multipath daemon configuration that enables 'user_friendly_names', as in:
```
WARNING: Invalid configuration: 'user_friendly_names' is enabled in multipath configuration:
defaults {
key value
user_friendly_names yes
}
device {
user_friendly_names yes
key value
}
This configuration is not supported and may lead to storage domain corruption.
```
=> tool.multipath: warn when user_friendly_names is enabled

docker/network/functional/Dockerfile.centos-9, docker/network/integration/Dockerfile.centos-9, docker/network/unit/Dockerfile.centos-9
DNF COPR started using 'epel-9-x86_64' chroot by default on CentOS 9 Stream since [this PR](https://github.com/rpm-software-management/dnf-plugins-core/pull/459) got merged. We publish built packages under 'centos-stream-9-x86_64', so let's select it explicitly.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
=> containers: Specify the chroot for COPR explicitly

.github/workflows/containers.yml, .github/workflows/network.yml, docker/network/functional/Dockerfile.alma-9, docker/network/integration/Dockerfile.alma-9, docker/network/unit/Dockerfile.alma-9
net: run tests on alma-linux 9.0
Alma Linux 9.0 is more stable and should provide consistent feedback
for the tests until we fix all el9-stream issues related to networking.
Create an Alma Linux 9.0 docker file, create a container from this file
and publish it to quay; run all tests in this container.
=>  net: run tests on alma-linux 9.0 

docker/network/Makefile
Alma Linux 9.0 is more stable and should provide consistent feedback
for the tests until we fix all el9-stream issues related to networking.
Create Alma Linux 9.0 docker files, create corresponding containers
tagged alma-9 and publish them to quay; run all tests on the alma-9
containers.
Change-Id: I7e18a5e1c0cda6315339aeb3a61ae3768e2fe859
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
=> net: run tests on alma-linux 9.0 - fix makefile

lib/vdsm/storage/fileVolume.py, tests/storage/localfssd_test.py
File volume create calls do not consider
preallocation policy for qcow2 format, which
are thin provisioned regardless.
Vdsm should do as commanded by the engine and
create a preallocated volume, both for raw and
qcow2 volumes.
Fixes: https://github.com/oVirt/vdsm/issues/292
=> fileVolume: consider preallocation for qcow

lib/vdsm/storage/blockVolume.py
In calculate_volume_alloc_size, there are
a couple comments that hint for the volume
format being qcow.
However, the code that is executed below the
preallocated comment, can be reached
also with a raw volume.
Edit the comment to include preallocated
raw option to avoid confusion.
=> blockVolume: remove misleading comments

docker/requirements.txt
Add userstorage as a required package to allow
using the most recent version from PyPI.
=> requirements: add userstorage

tox.ini
Add storage-user and storage-root environments,
and remove storage in tox.ini, so that the listed
environments match the supported ones.
Fixes: 6fa5937a9b763ed0f9cbbf861e1ebd6b813d8074
Fixes: 395a3d6d54afc34781c19e09b3d6f8316f4593b7
=> tox.ini: fix envlist

tests/storage/merge_test.py
Increase the size of the volumes created in the
reduce tests in the merge_test module, so that
volume sizes are more realistic.
Consequently, chunked leaf volumes do not reduce
anymore in the test. Chunked leaf volumes add an
extra chunk to the required size as the condition
to call reduce.
The test relied in the allocation
that Vdsm does when the volume is created
in `calculate_volume_alloc_size` if the create
call does not specify an initial size.
In that case, Vdsm allocates an entire chunk,
whereas the requested capacity was smaller (test
requested 2 GiB volumes, Vdsm allocated 2.5 GiB).
As long as the required size is smaller
than the difference between capacity and
chunk size (0.5 GiB), reduce will be called
during finalizeMerge.
In a real setup, tests show that leaf volumes
are not …
=> merge_test: increase reduce vol size

lib/vdsm/storage/blockVolume.py, tests/storage/blocksd_test.py, tests/storage/blockvolume_test.py
For block sparse volumes, if no initial_size is
defined, Vdsm allocates one chunk (2.5G), without
considering the virtual size of the volume.
This results in wasted space if the requested
volume is smaller.
Instead, we can allocate the capacity when
it is smaller than one chunk, to avoid wasting
space for small volumes.
Note than any size smaller than one extent
(128M) will be rounded to the extent size.
Bug-Url: https://bugzilla.redhat.com/2094576
=> blockVolume: fix over allocation of small volumes

static/usr/share/vdsm/lvmlocal.conf
Metadata header comments of the lvmlocal.conf
file are parsed by the vdsm-tool when running
the is-configured command. This check is
failing due to an empty line between the license
headers and the actual header with the metadata,
which is processed as a premature end of the
header.
Connect the SPDX header lines with the rest of
the header by adding a `#` character at the
beginning.
=> lvmlocal.conf: fix header metadata

tests/tool_configurators_lvm_test.py, tox.ini
Recent change adding spdx headers broke OST. Add simple test ensuring that the builtin file can be parsed.
=> tests: Test builtin lvmlocal.conf

.github/workflows/ci.yml, docker/Dockerfile.centos-9, docker/Makefile
Add centos-stream-9 Dockerfile to the
docker folder so that it can be built,
and used in the pipelines.
=> CIs: test with el9stream

lib/vdsm/storage/lvmdevices.py
Create empty devices file even if no lvm
volumes are found with
`vdsm-tool config-lvm-filter`.
Otherwise configuring LVM to use a devices
file without the file allows lvm commands
to see all volumes, with the associated risk.
Bug-Url: https://bugzilla.redhat.com/2125290
=> lvmdevices: always create devices file

lib/vdsm/storage/lvmdevices.py
Create empty devices file even if no lvm
volumes are found with
vdsm-tool config-lvm-filter.
Otherwise configuring LVM to use a devices
file without the file allows lvm commands
to see all volumes, with the associated risk.
Bug-Url: https://bugzilla.redhat.com/2125290
Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)
=> Backport: lvmdevices: always create devices file

Makefile.am, static/etc/sudoers.d/50_vdsm.in, static/usr/share/vdsm/autounattend/Autounattend.xml.in, vdsm_hooks/extra_ipv4_addrs/sudoers, vdsm_hooks/localdisk/sudoers.vdsm_hook_localdisk, vdsm_hooks/openstacknet/sudoers.in, vdsm_hooks/vhostmd/sudoers.vdsm_hook_vhostmd
The recently added SPDX headers cause some problems with downstream builds:
- SPDX headers in sudoers files require security review.
- SPDX headers in autounattended files report linting failure because the files don’t start with an XML header at the very beginning.
Let’s remove SPDX headers from the given places to avoid false alerts. Let’s also disable ‘reuse’ check in ‘make lint’ to avoid linter failures due to missing SPDX headers.
This is 4.5.3-only change to avoid problems with downstream builds.
=> Remove SPDX headers from sensitive files

static/usr/share/vdsm/autounattend/Autounattend.xml.in
A valid XML should start with the declaration and only then comments are allowed.
=> reuse: Put SPDX after XML declaration

Makefile.am, static/etc/sudoers.d/50_vdsm.in.license, static/usr/share/vdsm/autounattend/Autounattend.xml.in, vdsm_hooks/extra_ipv4_addrs/sudoers.license, vdsm_hooks/localdisk/sudoers.vdsm_hook_localdisk.license, vdsm_hooks/openstacknet/sudoers.in.license, vdsm_hooks/vhostmd/sudoers.vdsm_hook_vhostmd.license
Let’s improve the recent SPDX workarounds:
- Put back SPDX to Autounattend.xml.in, just at the right place.
- Add *.license files to sudoers files to avoid modifying the files directly.
- Re-enable running ‘reuse’ linter check by default.
=> reuse: Cleanup of SPDX handling

doc/development.md
First draft for including coding guidelines in the project.
=> development.md: add coding guidelines

lib/vdsm/gluster/cli.py, tests/glusterGeoRepStatus.xml, tests/glusterGeoRepStatusOld.xml, tests/glusterGeoRepStatusOld.xml.license, tests/glusterTestData.py, tests/gluster_cli_test.py
Since the upgrade to oVirt 4.5 and GlusterFS 10, information about snapshots and geo replication are no more visible on the engine Webui. After digging VDSM logs, I found that it's caused by the change of some XML elements name introduced in a new Gluster release (https://github.com/gluster/glusterfs/pull/1568) and by the addition of the timezone in output of status command.
This commit fix the parsing process of the output returned by gluster command, so that data sent to ovirt engine are as expected.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=2104278
=> Fix missing informations on geo replication tab of GlusterFS volumes.

lib/vdsm/storage/lvmdevices.py
Current implementation assumes /etc/lvm/devices folder exists, which may not be true with a fresh installation (only in an upgrade).
We need to make sure that we create the directory
before creating the empty devices file, with
exist_ok flag set to True. This will ensure
that it works in both scenarios.
Fixes: b8692e93f38abaed973c528fe457a767cc1245ea
=> lvmdevices: create devices directory

lib/vdsm/virt/qemuguestagent.py
If guest agent returns None for vCPU count, TypeError is raised. This patch adds correct handling of this situation.
Bug-Url: https://bugzilla.redhat.com/2120381
Signed-off-by: Shmuel Melamud <smelamud@redhat.com>
=> virt: Accept None returned by guest agent for vCPU count

lib/vdsm/storage/operation.py, lib/vdsm/storage/qemuimg.py
Add flag warn_stderr to Command class to
log to WARNING level instead of DEBUG
level if the command execution has data
in the stderr output, even if the command
finished succesfully.
Also, the logged message changes if the
new warn_stderr flag is set, printing
the command that originated the error
output.
Legacy debug logging remains unchanged.
ProgressCommand in qemuimg will enable
the flag so that qemuimg commands show
warning on errors.
Example:
```
09:49:34,851 WARNING (MainThread) [storage.operation] Command
['/usr/bin/qemu-img', 'commit', '-p', '-t', 'none', '-b'...]
succeeded with warnings: bytearray(b"qcow2_free_clusters failed: No space left on
device\nqemu-img: Lost persistent bitmaps during inactivation of node \'#block365\':
Failed to write bitmap \'stale-bitmap5\' to file: No …
```
=> qemuimg: log warning on cmd error

lib/vdsm/storage/bitmaps.py, lib/vdsm/storage/merge.py, tests/storage/bitmaps_test.py, tests/storage/blocksd_test.py
Prune the stale base volume bitmaps during
the prepare step on a merge operation.
These stale bitmaps can cause the merge
operation to fail due to 'No space left on device'.
In this case, qemu does not end with error, so
the failure goes unnoticed.
As there is not a reliable way to measure
the size of these stale bitmaps, and they are
invalid and can never be used for incremental
backup, it is better to prune them to avoid
the error.
Related: https://github.com/oVirt/vdsm/issues/352
=>  cold merge: prune stale bitmaps in base volume

lib/vdsm/storage/resourceManager.py
Fix various exceptions in the resourceManager module, so that
it is constructed wiht f-string instead of %-format.
Fix `ResourceAlreadyAcquired` exception that is
using a comma to separate instead of `%`, resulting in
bogus printed message.
Before:
```
vdsm.storage.resourceManager.ResourceAlreadyAcquired: ('%s is already
acquired by %s', '00_storage.a2ad7a23-96c5-4c23-9007-c0d1892ea07d',
'fb7c6873-74b4-4895-876a-a52ab7bfa082')
```
After:
```
vdsm.storage.resourceManager.ResourceAlreadyAcquired:
'00_storage.a2ad7a23-96c5-4c23-9007-c0d1892ea07d is already
acquired by fb7c6873-74b4-4895-876a-a52ab7bfa082'
```
=> resourceManager: use f-strings in exceptions

lib/vdsm/storage/hsm.py, lib/vdsm/virt/livemerge.py, lib/vdsm/virt/vm.py, tests/virt/livemerge_test.py, tests/virt/vmfakelib.py
Prune stale bitmaps before a live merge to avoid
failing with ENOSPC.
Fixes: #352
=> livemerge: prune bitmaps before measuring

lib/vdsm/storage/bitmaps.py, lib/vdsm/storage/hsm.py, lib/vdsm/storage/merge.py, lib/vdsm/storage/operation.py, lib/vdsm/storage/qemuimg.py, lib/vdsm/storage/resourceManager.py, lib/vdsm/virt/livemerge.py, lib/vdsm/virt/vm.py, tests/storage/bitmaps_test.py, tests/storage/blocksd_test.py, tests/virt/livemerge_test.py, tests/virt/vmfakelib.py
Commits/PRs cherry picked for backporting (in order):
- https://github.com/oVirt/vdsm/pull/356 (1 commit)
- https://github.com/oVirt/vdsm/pull/354 (3 commits)
- https://github.com/oVirt/vdsm/pull/358 (first commit only, the rest were not relevant)
- https://github.com/oVirt/vdsm/pull/357 (4 commits)
Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)
=> backport: prune bitmaps fix

.github/workflows/containers.yml, docker/Dockerfile.alma-9, docker/Makefile
Build also vdsm test containers in the weekly
build workflow.
Add another job to the containers workflow
to build and upload test containers
in `docker` directory.
For test containers, build each distro
separately and push it to the same
repository with a different tag.
Final tree of Vdsm repositories:
```
.
└── ovirt/
├── ovirt-vdsm-network-tests-functional:
│   ├── centos-8
│   ├── centos-9
│   └── alma-9
├── ovirt-vdsm-network-tests-integration:
│   ├── centos-8
│   ├── centos-9
│   └── alma-9
├── ovirt-vdsm-network-tests-unit:
│   ├── centos-8
│   ├── centos-9
│   └── alma-9
└── ovirt-test:
├── centos-8
├── centos-9
└── alma-9
```
=> ci/container.yml: build also vdsm-test containers

docker/Dockerfile.alma-9, docker/Dockerfile.centos-8, docker/Dockerfile.centos-9
In vdsm-test containers, create a
new venv [1] at /venv instead of installing
the required packages directly in the
root environment. Installing packages in
the root environment is strongly discouraged,
as it can run into conflicts with the system
package manager.
[1] - https://pip.pypa.io/warnings/venv
=> docker: create venv for tests

.github/workflows/containers.yml
Local image name of the vdsm-test containers
is `vdsm-test:tag`. However, the containers test job, mimicking the network job, has `ovirt/vdsm-test` as the image name. As a result, when the job tries to upload the image, it fails to find it locally.
It should be just `vdsm-test`. The upload job will store the image for the oVirt user under
`ovirt/vdsm-test:tag` repository, as expected.
Fixes: 533322126010366da334d11980df4e1a525cf797
=> containers: fix local image name

.github/workflows/containers.yml, docker/Makefile
Make vdsm-network and vdsm-test container
local tag consistent. This will make it easier
to handle in the containers github workflow.
Before:
ovirt/vdsm-network-tests
vdsm-test
After:
ovirt/vdsm-network-tests
ovirt/vdsm-test
Fixes: 533322126010366da334d11980df4e1a525cf797
=> containers: test and network name consistency

vdsm.spec.in
OvS 2.17 and OVN 2.19 are the lowest supported versions on EL9, so we
need to bump the requirements. But OvS 2.15 and OVN 2021 are the
supported versions on EL8, no changes there.
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Bump OvS to 2.17 and OVN to 2.19 on EL9

lib/vdsm/virt/qemuguestagent.py, tests/virt/qemuguestagent_test.py
In commit 45903d01e142047093bf844628b5d90df12b6ffb there was code added to refresh the fs info earlier when a hotplug disk was added. Now this caused some side effect that when only that command was triggered, the info dict never contained 'disk.count', which caused us to change the diskMapping to the parsed data from fsinfo.
Some minutes later when the disk command needed to be refreshed, it changed the diskMapping again, because (sometimes) the disks call returns more disks in comparision to the fsinfo call (for ex unmounted disks).
Again a bit later, the fsinfo had to be refreshed, and the diskMapping was modified again.
This occurs continiously, causing the device hash to change every time, and causing an excessive amount of dumpxml's also due to that.
Fixed this by not setting the …
=> Fix flapping disk info due to timing differences

.github/workflows/codeql-analysis.yml, .github/workflows/containers.yml, .github/workflows/network.yml
Version 2 of the checkout action produces a warning and cancels the action. Upgrading to version 3.
Change-Id: I6f80aeae400104a188615444ca3bdbbcc8817898
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
=> github actions: upgrade to checkout version 3

lib/vdsm/storage/blockVolume.py, lib/vdsm/storage/fileVolume.py, lib/vdsm/storage/volume.py, tests/storage/blocksd_test.py
Currently we assume in the code that cow
volumes do not need to be extended in any case.
However, all preallocated volumes, both
cow and raw, should be extended when requested.
Otherwise, cow preallocated volumes have bigger
capacity than their truesize. Thus, when the size
of the disk reaches the truesize, the VM will
pause, which is an undesired effect.
To avoid this, we relax this assumption so that
only cow sparse volumes are skipped on extend calls.
Bug-Url: https://bugzilla.redhat.com/2170689
=> volume: allow extend cow preallocated

docker/Dockerfile.alma-9, docker/Dockerfile.centos-8, docker/Dockerfile.centos-9
Create virtual environment for vdsm-test container with
system packages.
Otherwise, el9 containers have missing
dependencies.
Fixes: cd4425e
=> docker: python system packages

.github/workflows/ci.yml, Makefile.am, ci/lint.sh, ci/tests-storage.sh, ci/tests.sh, tests/pywatch_test.py, tox.ini
Update the cis workflow to use the new vdsm-test
container at quay.io/ovirt/vdsm-test:<distro>.
Modify the test scripts to activate the venv
before running the tests, otherwise the tests
will have missing dependencies that are only
installed in the venv in the new containers.
=> ci: use new vdsm-test container

lib/vdsm/storage/volume.py, tests/storage/blocksd_test.py
Small fixes over https://github.com/oVirt/vdsm/pull/379
=> volume: extend preallocate small fixes

ci/rpm.sh
This is necessary to prevent
fatal: detected dubious ownership in repository at '/__w/vdsm/vdsm'
messages in the CentOS Stream 9 container and, more importantly, making wrong rpm release version there when building rpm’s.  Without this, the determined release version on CI is always ‘1’, which results in not installing the required set of rpm’s in OST and an OST failure.
=> ci: Mark the current git directory as safe

lib/vdsm/storage/managedvolume.py
"local" connections are used by storage systems that directly set up devices on vdsm nodes, such as linstor[1]
[1]: https://docs.openstack.org/cinder/latest/configuration/block-storage/drivers/linstor-driver.html
=> managedvolume: add support for local device

lib/vdsm/storage/volume.py, tests/storage/filevolume_test.py
Consider format also on the skip condition
for extending volumes. Only COW sparse volumes
shall be skipped.
Fixes: https://github.com/oVirt/vdsm/commit/c9d6da42bc43e863c3110d78769595785f35fc07
Bug-Url: https://bugzilla.redhat.com/2210036
=> volume: Extend raw sparse

lib/vdsm/storage/volume.py, tests/storage/filevolume_test.py
Consider format also on the skip condition
for extending volumes. Only COW sparse volumes
shall be skipped.
Fixes: https://github.com/oVirt/vdsm/commit/c9d6da42bc43e863c3110d78769595785f35fc07
Bug-Url: https://bugzilla.redhat.com/2210036
=> Backport: volume: extend raw sparse

lib/vdsm/api/vdsm-api.yml, lib/vdsm/host/caps.py, lib/vdsm/storage/volume.py, tests/storage/blocksd_test.py, tests/storage/localfssd_test.py, tests/storage/sdm_add_bitmap_test.py, tests/storage/sdm_clear_bitmaps_test.py, tests/storage/sdm_copy_data_test.py, tests/storage/sdm_merge_test.py, tests/storage/sdm_remove_bitmap_test.py
We add bitmap info the the getQemuImageInfo output so this can be used within ovirt-engine.
This might be a cleaner alternative to https://github.com/oVirt/vdsm/pull/393
As we just extend the existing call to also return the bitmap info.
=> Add bitmap info to getQemuImageInfo

lib/vdsm/virt/vm.py
When disk replication fails during live storage migration, we detect it properly, fail the operation and remove the disk from the destination storage domain. However, we didn't tear down the replica on the host that executes the replication and therefore, if the removal of the destination disk was done on a different host, we had leftovers remaining on the host that executed the replication.
This patch changes the diskReplicateFinish function to tear down the replicate when the corresponding block job doesn't exist in order to prevent this scenario of having leftovers on the host that could lead to data corruption later on.
Bug-Url: https://bugzilla.redhat.com/2193392
=> Teardown replica when replication fails

lib/vdsm/network/nmstate/ovs/network.py, lib/vdsm/storage/formatconverter.py, lib/vdsm/storage/sd.py, lib/vdsm/tool/configurators/libvirt.py, tests/schemavalidation_test.py, tests/virt/vmoperations_test.py, vdsm_hooks/scratchpad/before_vm_start.py
While the difference between X not in Y and not X in Y may be negligible from a performance standpoint, using a more direct form can in some cases make it easier for the code optimizer in the Python interpreter.
=> fix_Flake8_Rules_E713

lib/vdsm/taskset.py, tests/virt/domaindescriptor_test.py
Issue: The CPU pinning tool tip says that to exclude a cpu from pinning, it needs to provided in the following format.
0#10-13_1#25-27,^26
With this format CPU 26 will be excluded from pinning. However, vdsm code fails to parse the above string resulting in VM start failure.
Fix: Fix the cpu pinning parsing logic to parse the format appropriately and exclude cpu from pinning list.
Signed-off-by: ShubhaOracle <Shubha.kulkarni@oracle.com>
=> Fix the cpu pinning parsing logic to parse the format appropriately and exclude cpu from pinning list

lib/vdsm/storage/storageServer.py, tests/storage/storageserver_test.py
The function _get_gluster_volinfo query the glusterfs volume info the the storage server, this is translated to the gluster client adding the parameter --remote-host which limits the query to one server, so we are converting the storage server as a single point of failure, if it is not available, it can led to cluster outtage. The proposed changed let the cluster cli to use any available gluster peer.
=> vdsm: get gluster volume info from any gluster peer

lib/vdsm/storage/storageServer.py, tests/storage/storageserver_test.py
The function _get_gluster_volinfo query the glusterfs volume info the the storage server, this is translated to the gluster client adding the parameter --remote-host which limits the query to one server, so we are converting the storage server as a single point of failure, if it is not available, it can led to cluster outtage. The proposed changed let the cluster cli to use any available gluster peer.
Bug-Url: https://bugzilla.redhat.com/2264175
Signed-off-by: José Enrique Gutiérrez Mazón <josgutie@redhat.com>
=> Backport: get gluster volume info from any gluster peer

lib/vdsm/virt/vmdevices/network.py, tests/virt/devicexml_test.py
There was some logic error in the update_bandwidth_xml function. If you have a running VM with a NIC that has a QoS, it will contain a bandwidth setting in the XML.
Now if you change the NIC to a vNIC Profile without QoS, it will not contain the 'inbound' and 'outbound' specParams, and the old QoS will never get removed (only after stop/start).
So we take the removal of the bandwidth out of the if so the limit gets cleared correctly.
=> virt: remove bandwidth limit on nic update

lib/vdsm/osinfo.py, lib/vdsm/storage/lvm.py, tests/lib/osinfo_test.py, tests/storage/lvm_test.py
Since LVM v2.03.17 (https://github.com/lvmteam/lvm2/commit/f6f2737015746b1b6c7fbd0d297a4596c584749b), reducing a logical volume (LV) requires the LV to be active due to the default 'checksize' option, which requires an active LV. This results in the following error when attempting to reduce a non-active LV:
`err=[\'  The LV must be active to safely reduce (see --fs options.)\']' ----`
To resolve this, we now check if the LVM version is newer than 2.03.17. If so, we bypass the 'checksize' by using the '--fs ignore' option. This approach is viable because oVirt already handles checksize, making lvreduce redundant.
=> Skip LVM filesystem check on LV reduction

lib/vdsm/common/dsaversion.py.in
This patch adds support for cluster compatibility level 4.8. Support for cluster compatibility level 4.8 is reported when the libvirt version >= 9.5.0 and qemu-kvm version >= 8.1.0. This version of libvirt adds support for the discard-no-unref option in qemu (https://patchew.org/QEMU/20230602124747.1544077-1-jean-louis@dupond.be/)
Corresponding PR: https://github.com/oVirt/ovirt-engine/pull/938
=> Add support for cluster level 4.8

tox.ini
There is an incompatibility between packaging version from CentOS and setuptools from pip. Which causes a failure running the tests: TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
See also https://github.com/pypa/setuptools/issues/4483
Fix this by using a the current packaging version instead of the CentOS packaged one.
=> tests: add dep on packaging in tox

lib/vdsm/virt/libvirtxml.py
Add the 'generic virtual board model' for aarch64 support.
Currently there is no aarch64 board supported in vdsm/_DEFAULT_MACHINES and according to the qemu documentation
https://qemu-project.gitlab.io/qemu/system/arm/virt.html
'virt' seems to be the recommended generic board model for this platform.
=> aarch64: add default image

lib/vdsm/common/dsaversion.py.in
Update the versions of libvirt and qemu that are required for cluster version 4.8.
=> conf: upgrade 4.8 version check
