oVirt/vdsm

tests/virt/vmmigration_test.py

- Add an explaining comment to the empty pause code.
- Test NOERR pause code.

tests: virt: Improve test_migrate_from_status

---

tests/lib/yajsonrpc/jsonrpcserver_test.py
tests/lib/yajsonrpc/stomp_test.py
tests/lib/yajsonrpc/stomprpcclient_test.py

We don't use jenkins CI anymore.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

tests: yajsonrpc: Use TRAVIS_CI on broken tests

---

.github/workflows/codeql-analysis.yml

The current version is obsolete and fails.  Let's update according to
https://github.com/github/codeql-action

github: Update codeql-analysis workflow

---

lib/vdsmclient/client.py

The current url is giving a 404 as this file is moved to lib/vdsm/api. This PR is to correct the URL only

updated url for vdsm-api.yml

---

lib/vdsm/tool/configurators/passwd.py
tests/tool_test.py

currently Passwd use sha-1 which is deprecated, we should move to
sha-256.

update passwd to use scram-sha-256

---

vdsm.spec.in

Point to the tarball included in the release archive

spec: point to src URL

---

tests/virt/vmstorage_test.py

The way we set and clear exceeded time is little too delicate. Lets
protect with it with a test.
The new test added as simple function since the relevant class was was
not converted properly to pytest, and we cannot use pytest fixtures in
the class. Converting the module to pytest properly will have to be done
later.
Completes #80.

tests: Test drive exceeded time behavior

---

CODEOWNERS

Moving to different project, removing myself from code owners not to
block code reviews.

CODEOWNERS: Remove me from code owners

---

lib/vdsm/storage/sdm/api/copy_data.py

As a result of commit 8dc293a (copy_data: skip locking source when same image is used), a regression was introduced, breaking copy_data operations involving endpoints that aren't DIV, currently only affects external endpoints as this is the only other endpoint type.
Because the external endpoint does not have the img_id property, it will fail:
```
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/vdsm/storage/task.py", line 884, in _run
return fn(*args, **kargs)
File "</usr/lib/python3.6/site-packages/decorator.py:decorator-gen-199>", line 2, in sdm_copy_data
File "/usr/lib/python3.6/site-packages/vdsm/common/api.py", line 50, in method
ret = func(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/vdsm/storage/hsm.py", line 3357, in sdm_copy_data …
```

copy_data: only skip lock for div endpoint

---

tests/storage/mailbox_test.py

- Verify roundtrip test results
- Refine mailbox roundtrip tests
- Add roundtrip test when events are disabled

Improve mailbox tests

---

tests/README

Move tox-recreate command to troubleshooting.

Update tests README.

---

.github/workflows/ost.yml

The removed logic has been implemented on OST side.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

Update OST trigger

---

tests/storage/outofprocess_test.py

outofprocess_test: 'External API' block to use userstorage

---

lib/vdsm/common/config.py.in
lib/vdsm/virt/qemuguestagent.py
tests/virt/qemuguestagent_test.py

Bug-Url: https://bugzilla.redhat.com/2077008
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>

qemuguestagent: store CPU count reported by guest

---

lib/vdsm/storage/managedvolume.py

* Extract the supported drivers tuple to a variable to make it easier to add drivers in the future
* Add lightos to the supported drivers

managedvolume: Add lightos support

---

.github/workflows/network.yml

Disable functional tests until all related issues are solved.
Change-Id: Ifb6d0b32c90161b4ab088cda74915a5bfd64cd7b
Signed-off-by: Eitan Raviv <eraviv@redhat.com>

network: centos-9 disable functional tests

---

configure.ac
execcmd-allowlist.txt
vdsm.spec.in
vdsm_hooks/Makefile.am
vdsm_hooks/log_console/Makefile.am
vdsm_hooks/log_console/README
vdsm_hooks/log_console/before_vm_start.py

Change-Id: I2965b5925eefea4f4c1d58fc89c404e034f8e3e7
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

hooks: Add log_console

---

doc/development.md
tests/README.md

Clarified the order of things in the development docs.
Bug-Url: not a bug, has no associated ticket
Signed-off-by: Rob Linden rlinden@redhat.com

Clarified the development and tests md.

---

lib/vdsm/virt/vm.py

Revived patch that originated on Gerrit: https://gerrit.ovirt.org/c/vdsm/+/115784. My changes to the code were minimal and only addressing reviewers comments so I have left the `Signed-off-by` line from @vjuranek intact.
---
When the VM is stopped on the source after migration, set VM status to
Down and also switch domain to Defined state. The domain is not running
and not all calls are available -- some would result in libvirt error.
Defined domain will throw virdomain.NotConnectedError which should be
handled by the caller.
Added handling of this exception into Vm._destroyVm* methods.
The methods are not called on not connected domain so this is only a
preventive measure to be on the safe side.
Bug-Url: https://bugzilla.redhat.com/2000046
Signed-off-by: Vojtech Juranek …

virt: switch domain to Defined once migrated VM is stopped

---

tests/network/functional/bridge_test.py

Change-Id: I120ae79d46006f4a7c0eafc319cceb03b8c030b0
Signed-off-by: Eitan Raviv <eraviv@redhat.com>

network: bridge_opts - test priority option recognized

---

tests/storage/localfssd_test.py

The test for cow preallocated volumes in
file storage was checking that the actual-size
is bigger than virtual-size for the resulting
volume, as reported by `qemu-img`. However, this
check is not robust enough, and may fail as we
do not really control the allocation between the
image start (at byte 0), and the initial image
end offset.
We need to obtain the initial image end offset
and subtract it from the virtual-size, to ensure
that the resulting image size is bigger
than the allocated bytes (`virtual-size - offset`).
To get the initial image end offset, create
a reference cow image of the same size as the
volume, and use `qemu-img check` on it.

localfssd_test: fix cow prealloc check

---

tests/storage/tmpstorage.py

Since we moved to lvm devices, tmpstorage teardown is broken, and does not deactivate and remove vgs during teardown. After running a test creating a temporary loop device and creating a storage domain, the storage domain lvs are left active:
$ sudo dmsetup table
bae261e2--3bfb--473d--86df--a63f92375df7-ids: 0 262144 linear 7:0 526336
bae261e2--3bfb--473d--86df--a63f92375df7-inbox: 0 262144 linear 7:0 788480
bae261e2--3bfb--473d--86df--a63f92375df7-leases: 0 4194304 linear 7:0 1312768
bae261e2--3bfb--473d--86df--a63f92375df7-master: 0 2097152 linear 7:0 7604224
bae261e2--3bfb--473d--86df--a63f92375df7-metadata: 0 262144 linear 7:0 264192
bae261e2--3bfb--473d--86df--a63f92375df7-outbox: 0 262144 linear 7:0 1050624
bae261e2--3bfb--473d--86df--a63f92375df7-xleases: 0 2097152 linear 7:0 …

Fix tmpstorage teardown

---

lib/vdsm/storage/lvmdevices.py

Backport for https://github.com/oVirt/vdsm/pull/346 (1 commit).
Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)

Backport: create devices dir

---

.github/workflows/ci.yml
Makefile.am
ci/lint.sh
ci/tests-storage.sh
ci/tests.sh
tests/pywatch_test.py
tox.ini

Backport for https://github.com/oVirt/vdsm/pull/366

Backport CI flow

---

vdsm.spec.in

Releasing changes introduced over the past year

New release: 4.50.5.1

---

lib/vdsm/storage/mpathconf.py

flush_on_last_del yes is deprecated.
Replace it with non-deprecated value:
flush_on_last_del always

storage: fix deprecated value for flush_on_last_del
